
DELETE http://localhost:3003/api/persons/5f4069e7cc92a6e7f2df83cb HTTP/1.1

###

GET http://localhost:3003/api/persons

###
POST http://localhost:3003/api/persons HTTP/1.1
Content-Type: application/json

{
    "name": "Alaba",
	"number": "0947599"
}

###
PUT http://localhost:3003/api/persons/5f3ffc5ef3cf40c84ab3794a HTTP/1.1
Content-Type: application/json

{
    "name": "CR7",
	"number": "094758"
}